package database

import (
	"context"
	"fmt"

	"github.com/rs/zerolog/log"
)

func RunMigrations(ctx context.Context, db *Database) error {
	migrations := []string{
		`CREATE TABLE IF NOT EXISTS organizations (
			id UUID PRIMARY KEY,
			name TEXT NOT NULL,
			slug TEXT NOT NULL UNIQUE,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
		)`,
		`CREATE TABLE IF NOT EXISTS users (
			id UUID PRIMARY KEY,
			email TEXT NOT NULL UNIQUE,
			password_hash TEXT NOT NULL,
			organization_id UUID NOT NULL REFERENCES organizations(id),
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
		)`,
		`CREATE TABLE IF NOT EXISTS sessions (
			id UUID PRIMARY KEY,
			user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			refresh_token TEXT NOT NULL,
			expires_at TIMESTAMP WITH TIME ZONE NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)`,
		`CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id)`,
		`CREATE INDEX IF NOT EXISTS idx_sessions_refresh_token ON sessions(refresh_token)`,
		`CREATE TABLE IF NOT EXISTS receipts (
			id UUID PRIMARY KEY,
			organization_id UUID NOT NULL REFERENCES organizations(id),
			user_id UUID NOT NULL REFERENCES users(id),
			file_path TEXT NOT NULL,
			status TEXT NOT NULL DEFAULT 'pending',
			raw_vendor_name TEXT,
			raw_amount NUMERIC,
			raw_date TIMESTAMP WITH TIME ZONE,
			raw_category TEXT,
			raw_confidence DOUBLE PRECISION,
			vendor_name TEXT,
			amount NUMERIC,
			receipt_date TIMESTAMP WITH TIME ZONE,
			category TEXT,
			confidence DOUBLE PRECISION,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
		)`,
		`CREATE INDEX IF NOT EXISTS idx_receipts_org_created ON receipts(organization_id, created_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_receipts_status ON receipts(status)`,
		`CREATE TABLE IF NOT EXISTS exceptions (
			id UUID PRIMARY KEY,
			receipt_id UUID NOT NULL REFERENCES receipts(id) ON DELETE CASCADE,
			organization_id UUID NOT NULL REFERENCES organizations(id),
			type TEXT NOT NULL,
			field TEXT NOT NULL,
			message TEXT NOT NULL,
			status TEXT NOT NULL DEFAULT 'open',
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
		)`,
		`CREATE INDEX IF NOT EXISTS idx_exceptions_org ON exceptions(organization_id)`,
		`CREATE INDEX IF NOT EXISTS idx_exceptions_receipt ON exceptions(receipt_id)`,
		`CREATE INDEX IF NOT EXISTS idx_exceptions_status ON exceptions(status)`,
		`CREATE TABLE IF NOT EXISTS rules (
			id UUID PRIMARY KEY,
			organization_id UUID NOT NULL REFERENCES organizations(id),
			condition_type TEXT NOT NULL,
			condition_value TEXT NOT NULL,
			action_type TEXT NOT NULL,
			action_value TEXT NOT NULL,
			is_active BOOLEAN NOT NULL DEFAULT true,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
		)`,
		`CREATE INDEX IF NOT EXISTS idx_rules_org ON rules(organization_id)`,
		`CREATE TABLE IF NOT EXISTS organization_members (
			id UUID PRIMARY KEY,
			organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			role TEXT NOT NULL DEFAULT 'member',
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			deleted_at TIMESTAMP WITH TIME ZONE,
			UNIQUE (organization_id, user_id)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_org_members_user ON organization_members(user_id) WHERE deleted_at IS NULL`,
		`CREATE INDEX IF NOT EXISTS idx_org_members_org ON organization_members(organization_id) WHERE deleted_at IS NULL`,
		`CREATE TABLE IF NOT EXISTS accountant_clients (
			id UUID PRIMARY KEY,
			accountant_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			client_organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			role TEXT NOT NULL DEFAULT 'reviewer',
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			deleted_at TIMESTAMP WITH TIME ZONE,
			UNIQUE (accountant_user_id, client_organization_id)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_accountant_clients_accountant ON accountant_clients(accountant_user_id) WHERE deleted_at IS NULL`,
		`CREATE INDEX IF NOT EXISTS idx_accountant_clients_client ON accountant_clients(client_organization_id) WHERE deleted_at IS NULL`,
		`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS slug TEXT NOT NULL DEFAULT 'temp'`,
		`ALTER TABLE organizations DROP CONSTRAINT IF EXISTS organizations_slug_key`,
		`ALTER TABLE organizations ADD CONSTRAINT organizations_slug_key UNIQUE (slug)`,
		`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE`,
		`ALTER TABLE organizations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS user_id UUID`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS file_path TEXT`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS raw_vendor_name TEXT`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS raw_amount NUMERIC`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS raw_date TIMESTAMP WITH TIME ZONE`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS raw_category TEXT`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS raw_confidence DOUBLE PRECISION`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS vendor_name TEXT`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS amount NUMERIC`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS receipt_date TIMESTAMP WITH TIME ZONE`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS category TEXT`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS confidence DOUBLE PRECISION`,
		`ALTER TABLE users ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMP WITH TIME ZONE`,
		`ALTER TABLE users ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active'`,
		`ALTER TABLE users ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'UTC'`,
		`UPDATE users SET status = 'active' WHERE status = 'pending_verification' AND email_verified_at IS NOT NULL`,
		`ALTER TABLE sessions ADD COLUMN IF NOT EXISTS refresh_token_hash TEXT`,
		`ALTER TABLE sessions ADD COLUMN IF NOT EXISTS ip_address TEXT`,
		`ALTER TABLE sessions ADD COLUMN IF NOT EXISTS user_agent TEXT`,
		`ALTER TABLE sessions ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMP WITH TIME ZONE`,
		`ALTER TABLE exceptions ADD COLUMN IF NOT EXISTS field TEXT`,
		`ALTER TABLE exceptions ADD COLUMN IF NOT EXISTS message TEXT`,
		`ALTER TABLE receipts DROP CONSTRAINT IF EXISTS receipts_status_check`,
		`UPDATE receipts SET status = 'pending' WHERE status NOT IN ('pending', 'processing', 'processed', 'needs_review', 'failed', 'error')`,
		`ALTER TABLE receipts ADD CONSTRAINT receipts_status_check CHECK (status IN ('pending', 'processing', 'processed', 'needs_review', 'failed', 'error'))`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS file_url TEXT`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS file_name TEXT`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'USD'`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS line_items JSONB NOT NULL DEFAULT '[]'`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS is_billable BOOLEAN NOT NULL DEFAULT false`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS is_reimbursable BOOLEAN NOT NULL DEFAULT false`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS needs_review BOOLEAN NOT NULL DEFAULT false`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'upload'`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS raw_extraction JSONB NOT NULL DEFAULT '{}'`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS user_corrections JSONB NOT NULL DEFAULT '{}'`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS raw_text TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS ai_output JSONB NOT NULL DEFAULT '{}'`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS file_hash TEXT`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS processing_state TEXT NOT NULL DEFAULT 'queued'`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS validation_confidence DOUBLE PRECISION NOT NULL DEFAULT 0`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS final_confidence DOUBLE PRECISION NOT NULL DEFAULT 0`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS processing_started_at TIMESTAMP WITH TIME ZONE`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS processing_finished_at TIMESTAMP WITH TIME ZONE`,
		`ALTER TABLE receipts ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE`,
		`ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE`,
		`ALTER TABLE sessions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()`,
		`ALTER TABLE sessions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()`,
		`CREATE TABLE IF NOT EXISTS rule_learning_events (
			id UUID PRIMARY KEY,
			organization_id UUID NOT NULL REFERENCES organizations(id),
			vendor TEXT NOT NULL,
			chosen_category TEXT NOT NULL,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
		)`,
		`CREATE INDEX IF NOT EXISTS idx_rule_learning_org_vendor ON rule_learning_events(organization_id, vendor)`,
		`CREATE TABLE IF NOT EXISTS vendor_aliases (
			id UUID PRIMARY KEY,
			organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			canonical_vendor TEXT NOT NULL,
			alias TEXT NOT NULL,
			normalized_alias TEXT NOT NULL,
			confidence DOUBLE PRECISION NOT NULL DEFAULT 1,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			deleted_at TIMESTAMP WITH TIME ZONE,
			UNIQUE (organization_id, normalized_alias)
		)`,
		`CREATE INDEX IF NOT EXISTS idx_vendor_aliases_org_alias ON vendor_aliases(organization_id, normalized_alias) WHERE deleted_at IS NULL`,
		`CREATE INDEX IF NOT EXISTS idx_vendor_aliases_canonical ON vendor_aliases(organization_id, canonical_vendor) WHERE deleted_at IS NULL`,
		`CREATE TABLE IF NOT EXISTS storage_objects (
			id UUID PRIMARY KEY,
			organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			receipt_id UUID REFERENCES receipts(id) ON DELETE SET NULL,
			path TEXT NOT NULL UNIQUE,
			file_hash TEXT,
			size_bytes BIGINT NOT NULL DEFAULT 0,
			content_type TEXT,
			retention_until TIMESTAMP WITH TIME ZONE,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			deleted_at TIMESTAMP WITH TIME ZONE
		)`,
		`CREATE INDEX IF NOT EXISTS idx_storage_objects_org_created ON storage_objects(organization_id, created_at DESC) WHERE deleted_at IS NULL`,
		`CREATE INDEX IF NOT EXISTS idx_storage_objects_receipt ON storage_objects(receipt_id) WHERE deleted_at IS NULL`,
		`CREATE INDEX IF NOT EXISTS idx_receipts_vendor ON receipts(vendor_name)`,
		`CREATE INDEX IF NOT EXISTS idx_receipts_amount ON receipts(amount)`,
		`CREATE INDEX IF NOT EXISTS idx_receipts_file_hash ON receipts(file_hash)`,
		`CREATE INDEX IF NOT EXISTS idx_receipts_date ON receipts(receipt_date)`,
		`CREATE INDEX IF NOT EXISTS idx_receipts_org_processing_state ON receipts(organization_id, processing_state)`,
		`CREATE INDEX IF NOT EXISTS idx_receipts_org_status_created ON receipts(organization_id, status, created_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_receipts_org_vendor ON receipts(organization_id, vendor_name)`,
		`CREATE INDEX IF NOT EXISTS idx_receipts_org_date ON receipts(organization_id, receipt_date DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_receipts_not_deleted ON receipts(organization_id, created_at DESC) WHERE deleted_at IS NULL`,
		`CREATE TABLE IF NOT EXISTS receipt_processing_jobs (
			id UUID PRIMARY KEY,
			receipt_id UUID NOT NULL REFERENCES receipts(id) ON DELETE CASCADE,
			organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			queue_job_id TEXT,
			processing_state TEXT NOT NULL DEFAULT 'queued',
			attempts INT NOT NULL DEFAULT 0,
			max_attempts INT NOT NULL DEFAULT 3,
			last_error TEXT,
			started_at TIMESTAMP WITH TIME ZONE,
			finished_at TIMESTAMP WITH TIME ZONE,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
		)`,
		`CREATE INDEX IF NOT EXISTS idx_processing_jobs_receipt ON receipt_processing_jobs(receipt_id)`,
		`CREATE INDEX IF NOT EXISTS idx_processing_jobs_org_state ON receipt_processing_jobs(organization_id, processing_state, created_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_processing_jobs_state ON receipt_processing_jobs(processing_state)`,
		`CREATE TABLE IF NOT EXISTS subscriptions (
			id UUID PRIMARY KEY,
			organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			plan TEXT NOT NULL DEFAULT 'free',
			status TEXT NOT NULL DEFAULT 'active',
			stripe_customer_id TEXT,
			stripe_subscription_id TEXT,
			current_period_start TIMESTAMP WITH TIME ZONE,
			current_period_end TIMESTAMP WITH TIME ZONE,
			cancel_at_period_end BOOLEAN NOT NULL DEFAULT false,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			deleted_at TIMESTAMP WITH TIME ZONE
		)`,
		`CREATE INDEX IF NOT EXISTS idx_subscriptions_org ON subscriptions(organization_id)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_subscriptions_org_active_unique ON subscriptions(organization_id) WHERE deleted_at IS NULL`,
		`CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions(status)`,
		`CREATE TABLE IF NOT EXISTS audit_logs (
			id UUID PRIMARY KEY,
			organization_id UUID REFERENCES organizations(id) ON DELETE SET NULL,
			user_id UUID REFERENCES users(id) ON DELETE SET NULL,
			action TEXT NOT NULL,
			entity_type TEXT NOT NULL,
			entity_id TEXT,
			ip_address TEXT,
			user_agent TEXT,
			metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
		)`,
		`CREATE INDEX IF NOT EXISTS idx_audit_logs_org_created ON audit_logs(organization_id, created_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action)`,
		`CREATE TABLE IF NOT EXISTS google_integrations (
			id UUID PRIMARY KEY,
			organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			google_account_email TEXT,
			access_token_encrypted TEXT NOT NULL,
			refresh_token_encrypted TEXT NOT NULL,
			token_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
			spreadsheet_id TEXT,
			spreadsheet_name TEXT,
			status TEXT NOT NULL DEFAULT 'connected',
			last_sync_at TIMESTAMP WITH TIME ZONE,
			last_error TEXT,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			deleted_at TIMESTAMP WITH TIME ZONE
		)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_google_integrations_org_active ON google_integrations(organization_id) WHERE deleted_at IS NULL`,
		`CREATE INDEX IF NOT EXISTS idx_google_integrations_status ON google_integrations(status)`,
		`CREATE TABLE IF NOT EXISTS email_forwarding_addresses (
			id UUID PRIMARY KEY,
			organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			address TEXT NOT NULL UNIQUE,
			status TEXT NOT NULL DEFAULT 'active',
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			deleted_at TIMESTAMP WITH TIME ZONE
		)`,
		`CREATE INDEX IF NOT EXISTS idx_email_forwarding_org ON email_forwarding_addresses(organization_id)`,
		`CREATE INDEX IF NOT EXISTS idx_email_forwarding_status ON email_forwarding_addresses(status)`,
		`CREATE TABLE IF NOT EXISTS bank_imports (
			id UUID PRIMARY KEY,
			organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			user_id UUID REFERENCES users(id) ON DELETE SET NULL,
			file_name TEXT NOT NULL,
			source TEXT NOT NULL DEFAULT 'csv',
			status TEXT NOT NULL DEFAULT 'uploaded',
			rows_total INT NOT NULL DEFAULT 0,
			rows_imported INT NOT NULL DEFAULT 0,
			last_error TEXT,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			deleted_at TIMESTAMP WITH TIME ZONE
		)`,
		`CREATE INDEX IF NOT EXISTS idx_bank_imports_org_created ON bank_imports(organization_id, created_at DESC) WHERE deleted_at IS NULL`,
		`CREATE INDEX IF NOT EXISTS idx_bank_imports_status ON bank_imports(status) WHERE deleted_at IS NULL`,
		`CREATE TABLE IF NOT EXISTS bank_transactions (
			id UUID PRIMARY KEY,
			organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			import_id UUID REFERENCES bank_imports(id) ON DELETE SET NULL,
			transaction_date DATE NOT NULL,
			description TEXT NOT NULL,
			normalized_description TEXT NOT NULL DEFAULT '',
			amount NUMERIC NOT NULL,
			currency TEXT NOT NULL DEFAULT 'USD',
			matched_receipt_id UUID REFERENCES receipts(id) ON DELETE SET NULL,
			match_confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
			status TEXT NOT NULL DEFAULT 'unmatched',
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			deleted_at TIMESTAMP WITH TIME ZONE
		)`,
		`CREATE INDEX IF NOT EXISTS idx_bank_tx_org_date ON bank_transactions(organization_id, transaction_date DESC) WHERE deleted_at IS NULL`,
		`CREATE INDEX IF NOT EXISTS idx_bank_tx_org_status ON bank_transactions(organization_id, status) WHERE deleted_at IS NULL`,
		`CREATE INDEX IF NOT EXISTS idx_bank_tx_org_amount ON bank_transactions(organization_id, amount) WHERE deleted_at IS NULL`,
		`CREATE INDEX IF NOT EXISTS idx_bank_tx_matched_receipt ON bank_transactions(matched_receipt_id) WHERE deleted_at IS NULL`,
		`CREATE TABLE IF NOT EXISTS verification_tokens (
			id UUID PRIMARY KEY,
			user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			token_hash TEXT NOT NULL UNIQUE,
			expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
			used_at TIMESTAMP WITH TIME ZONE,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
		)`,
		`CREATE INDEX IF NOT EXISTS idx_verification_tokens_hash ON verification_tokens(token_hash)`,
		`CREATE INDEX IF NOT EXISTS idx_verification_tokens_user ON verification_tokens(user_id)`,
		`CREATE TABLE IF NOT EXISTS password_reset_tokens (
			id UUID PRIMARY KEY,
			user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
			token_hash TEXT NOT NULL UNIQUE,
			expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
			used_at TIMESTAMP WITH TIME ZONE,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
		)`,
		`CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_hash ON password_reset_tokens(token_hash)`,
		`CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user ON password_reset_tokens(user_id)`,
		`CREATE TABLE IF NOT EXISTS usage_tracking (
			organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			month TEXT NOT NULL,
			receipts_processed INT NOT NULL DEFAULT 0,
			quota_warning_80_sent_at TIMESTAMP WITH TIME ZONE,
			quota_exhausted_sent_at TIMESTAMP WITH TIME ZONE,
			created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
			PRIMARY KEY (organization_id, month)
		)`,
		`CREATE TABLE IF NOT EXISTS daily_digest_runs (
			organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
			digest_date DATE NOT NULL,
			sent_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
			PRIMARY KEY (organization_id, digest_date)
		)`,
	}

	for i, m := range migrations {
		_, err := db.Pool.Exec(ctx, m)
		if err != nil {
			return fmt.Errorf("migration %d failed: %w", i+1, err)
		}
	}

	log.Info().Msg("Database migrations completed")
	return nil
}
